// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydogpnnsebqftvtjauaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlkb2dwbm5zZWJxZnR2dGphdWFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MzgzNDIsImV4cCI6MjA3NDAxNDM0Mn0.QhCQoEH8oCy5rAMjK9ZhCuQFHbCBa-36I5c9pm-VvEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});